"""Generate data/sample/catalog.jsonl and evaluation/golden_set/queries.yaml.

Deterministic: the same input (``sample_catalog_data.py``) always produces
byte-identical output. Re-run after any change to that file.

Item IDs are assigned sequentially in topic order: ``i_0001`` through
``i_0200``. IDs are opaque per ``docs/contracts.md`` § 0; nothing in the
system parses them.

Golden set: for each topic, the first three items are seeds and the remaining
seven are relevant. This makes the ground truth objective and falsifiable:
a working model clusters by topic, so querying with three seeds should
retrieve the other seven items of the same topic in the top-k.
"""

from __future__ import annotations

import json
import pathlib
import sys
from typing import Any

import yaml

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPTS_DIR = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPTS_DIR))

from sample_catalog_data import TOPICS  # noqa: E402

CATALOG_PATH = REPO_ROOT / "data" / "sample" / "catalog.jsonl"
GOLDEN_SET_PATH = REPO_ROOT / "evaluation" / "golden_set" / "queries.yaml"

SEED_COUNT = 3
K_FOR_EVAL = 10


def generate_catalog() -> list[dict[str, str]]:
    """Return the catalog as a list of dicts, in deterministic order."""
    items: list[dict[str, str]] = []
    counter = 1
    for topic in TOPICS:
        brands = topic["brands"]
        raw_items = topic["items"]
        category = topic["category"]
        for i, entry in enumerate(raw_items):
            title, description = entry
            items.append(
                {
                    "item_id": f"i_{counter:04d}",
                    "title": title,
                    "description": description,
                    "category": category,
                    "brand": brands[i % len(brands)],
                }
            )
            counter += 1
    return items


def write_catalog(items: list[dict[str, str]]) -> None:
    CATALOG_PATH.parent.mkdir(parents=True, exist_ok=True)
    lines = [json.dumps(item, ensure_ascii=False) for item in items]
    CATALOG_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_golden_set(items: list[dict[str, str]]) -> dict[str, Any]:
    """Return the golden set document."""
    queries: list[dict[str, Any]] = []
    idx = 0
    for topic in TOPICS:
        topic_size = len(topic["items"])
        ids = [it["item_id"] for it in items[idx : idx + topic_size]]
        idx += topic_size
        queries.append(
            {
                "id": f"q_{topic['slug']}",
                "topic": topic["slug"],
                "seed_item_ids": ids[:SEED_COUNT],
                "relevant_item_ids": ids[SEED_COUNT:],
            }
        )
    return {
        "version": 1,
        "k_for_eval": K_FOR_EVAL,
        "seed_count_per_query": SEED_COUNT,
        "notes": (
            "Auto-generated by scripts/generate_sample_catalog.py. "
            "Do not edit by hand; re-run after any catalog change."
        ),
        "queries": queries,
    }


def write_golden_set(doc: dict[str, Any]) -> None:
    GOLDEN_SET_PATH.parent.mkdir(parents=True, exist_ok=True)
    with GOLDEN_SET_PATH.open("w", encoding="utf-8") as f:
        yaml.safe_dump(doc, f, sort_keys=False, allow_unicode=True, width=100)


def main() -> int:
    items = generate_catalog()
    write_catalog(items)
    doc = generate_golden_set(items)
    write_golden_set(doc)

    summary = {
        "event": "sample_catalog.generated",
        "items": len(items),
        "topics": len(TOPICS),
        "queries": len(doc["queries"]),
        "catalog_path": str(CATALOG_PATH.relative_to(REPO_ROOT)),
        "golden_set_path": str(GOLDEN_SET_PATH.relative_to(REPO_ROOT)),
    }
    print(json.dumps(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
